### ISSUE TITLE
I'm getting white while on a thread and the reply box.

### ISSUE THREAD

**Issue by LostConnection** [jszklarz-haventec/makeitdark#31] opened 2019-07-26 00:12 UTC
Its working! But im getting white while on a thread and the reply box.

![2019-07-25_11-38-09](https://user-images.githubusercontent.com/35497308/61888166-124dd780-aed1-11e9-8d90-8f5577f4de02.png)

_Originally posted by @hioz12 in https://github.com/LostConnection/makeitdark/issues/27#issuecomment-515095963_

**Comment by LostConnection** [comment] 2019-07-26 07:26
@hioz12 I have addressed these issues and tested on a Windows machine. They're pushed to master.

**Comment by defmonk0** [comment] 2019-07-30 04:30
@LostConnection I can confirm this is working on Win10 Production 4.0.0 64-bit. The white bits mentioned in issue #32 are still there, but it's probably safe to close this one since these specific two were fixed by your update.

**Closed as completed** 2019-08-01 20:28 UTC
