### ISSUE TITLE
All Threads broken

### ISSUE THREAD

**Issue by turbohappy** [jszklarz-haventec/makeitdark#14] opened 2019-03-20 23:32 UTC
Seems that something was changed today by Slack that broke the "All Threads" view and everything is blinding white.

**Comment by juuba** [comment] 2019-04-08 04:59
Came in to say this aswell, here's a picture:

![image](https://user-images.githubusercontent.com/7961613/55699638-570e3b00-59d4-11e9-8c19-9f7be9aca5a1.png)

**Comment by LostConnection** [comment] 2019-04-11 06:45
Hi I am going to update the css to address this issue.

**Comment by LostConnection** [comment] 2019-04-12 03:07
@turbohappy @juuba I have merged a fix for this to master. If the issue is fixed for you we can close this.

**Comment by juuba** [comment] 2019-04-12 11:26
Works for me!

**Comment by LostConnection** [comment] 2019-04-12 11:59
Great, closing the issue

**Closed as completed** 2019-04-12 12:00 UTC
